version: '3.8'
services:

  postgresql:
    image: postgres:14.1
    container_name: postgresql
    restart: always
    volumes:
      - postgresql:/data/lib
    environment:
      - POSTGRES_DB=node
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '6000:5432'

volumes:
  postgresql: